version: "3"

services:
  voter:
    build: ./voting-app-voter
    command: python app.py
    volumes:
     - ./voting-app-voter:/app
    ports:
      - 5000:8080
    networks:
      - front-tier
      - back-tier

  dashboard-rest:
    build: ./voting-app-dashboard-rest
    command: nodemon
    volumes:
      - ./voting-app-dashboard-rest:/app
    ports:
      - 5001:8081
    networks:
      - front-tier
      - back-tier

  worker:
    build:
      context: ./voting-app-worker
    restart: on-failure
    environment:
      PG_PW: password123
      PG_USER: testuser1
      PG_DBNAME: votes
      PG_HOST: postgres
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - back-tier

  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: testuser1
      POSTGRES_DB: votes
    ports:
      - 5432:5432
    volumes:
      - ./setup-script/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
