---
apiVersion: v1
kind: Service
metadata:
  labels:
    apps: worker
  name: worker
  namespace: voting-app
spec:
  clusterIP: None
  selector:
    app: worker
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: voting-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        -
          image: voting-app_worker
          imagePullPolicy: Never
          name: worker
