# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vote.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vote.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nvote.proto\x12\x02pb\"\x1e\n\rWorkerRequest\x12\r\n\x05query\x18\x01 \x01(\t\"*\n\x0bVoteResults\x12\x0c\n\x04vote\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"%\n\x04Vote\x12\x0f\n\x07votedID\x18\x01 \x01(\x05\x12\x0c\n\x04vote\x18\x02 \x01(\t\"\x1c\n\nVoteStatus\x12\x0e\n\x06status\x18\x01 \x01(\t2\xc3\x01\n\x11VoteWorkerService\x12+\n\x08GetVotes\x12\x11.pb.WorkerRequest\x1a\x08.pb.Vote\"\x00\x30\x01\x12\x39\n\x0fGetVotesResults\x12\x11.pb.WorkerRequest\x1a\x0f.pb.VoteResults\"\x00\x30\x01\x12%\n\x07SetVote\x12\x08.pb.Vote\x1a\x0e.pb.VoteStatus\"\x00\x12\x1f\n\x07GetVote\x12\x08.pb.Vote\x1a\x08.pb.Vote\"\x00\x62\x06proto3')
)




_WORKERREQUEST = _descriptor.Descriptor(
  name='WorkerRequest',
  full_name='pb.WorkerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='pb.WorkerRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=48,
)


_VOTERESULTS = _descriptor.Descriptor(
  name='VoteResults',
  full_name='pb.VoteResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vote', full_name='pb.VoteResults.vote', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='pb.VoteResults.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=92,
)


_VOTE = _descriptor.Descriptor(
  name='Vote',
  full_name='pb.Vote',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='votedID', full_name='pb.Vote.votedID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vote', full_name='pb.Vote.vote', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=131,
)


_VOTESTATUS = _descriptor.Descriptor(
  name='VoteStatus',
  full_name='pb.VoteStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pb.VoteStatus.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['WorkerRequest'] = _WORKERREQUEST
DESCRIPTOR.message_types_by_name['VoteResults'] = _VOTERESULTS
DESCRIPTOR.message_types_by_name['Vote'] = _VOTE
DESCRIPTOR.message_types_by_name['VoteStatus'] = _VOTESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorkerRequest = _reflection.GeneratedProtocolMessageType('WorkerRequest', (_message.Message,), dict(
  DESCRIPTOR = _WORKERREQUEST,
  __module__ = 'vote_pb2'
  # @@protoc_insertion_point(class_scope:pb.WorkerRequest)
  ))
_sym_db.RegisterMessage(WorkerRequest)

VoteResults = _reflection.GeneratedProtocolMessageType('VoteResults', (_message.Message,), dict(
  DESCRIPTOR = _VOTERESULTS,
  __module__ = 'vote_pb2'
  # @@protoc_insertion_point(class_scope:pb.VoteResults)
  ))
_sym_db.RegisterMessage(VoteResults)

Vote = _reflection.GeneratedProtocolMessageType('Vote', (_message.Message,), dict(
  DESCRIPTOR = _VOTE,
  __module__ = 'vote_pb2'
  # @@protoc_insertion_point(class_scope:pb.Vote)
  ))
_sym_db.RegisterMessage(Vote)

VoteStatus = _reflection.GeneratedProtocolMessageType('VoteStatus', (_message.Message,), dict(
  DESCRIPTOR = _VOTESTATUS,
  __module__ = 'vote_pb2'
  # @@protoc_insertion_point(class_scope:pb.VoteStatus)
  ))
_sym_db.RegisterMessage(VoteStatus)



_VOTEWORKERSERVICE = _descriptor.ServiceDescriptor(
  name='VoteWorkerService',
  full_name='pb.VoteWorkerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=164,
  serialized_end=359,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetVotes',
    full_name='pb.VoteWorkerService.GetVotes',
    index=0,
    containing_service=None,
    input_type=_WORKERREQUEST,
    output_type=_VOTE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetVotesResults',
    full_name='pb.VoteWorkerService.GetVotesResults',
    index=1,
    containing_service=None,
    input_type=_WORKERREQUEST,
    output_type=_VOTERESULTS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetVote',
    full_name='pb.VoteWorkerService.SetVote',
    index=2,
    containing_service=None,
    input_type=_VOTE,
    output_type=_VOTESTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetVote',
    full_name='pb.VoteWorkerService.GetVote',
    index=3,
    containing_service=None,
    input_type=_VOTE,
    output_type=_VOTE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VOTEWORKERSERVICE)

DESCRIPTOR.services_by_name['VoteWorkerService'] = _VOTEWORKERSERVICE

# @@protoc_insertion_point(module_scope)
